trigger:
- master

strategy:
  matrix:
    linux:
      operatingSystem: 'ubuntu-latest'
    mac:
      operatingSystem: 'macos-latest'

pool:
  # vmImage: 'ubuntu-latest'
  vmImage: $(operatingSystem)

# stages:
# - stage: Build
# jobs:
# - job: BuildJob
steps:
- script: echo running on $(operatingSystem)
  displayName: "Run a 1-line script"
# - stage: DeployJob
#   jobs:
#   - deployment: DevDeployJob
#     environment: Dev
#     strategy: 
#       runOnce:
#         deploy:
#           steps:
#             - script: echo deploy to Dev
# - stage: QAJob
#   jobs:
#   - deployment: QADeployJob
#     environment: QA
#     strategy: 
#       runOnce:
#         deploy:
#           steps:
#             - script: echo deploy to QA

