trigger:
- master

strategy:
  # matrix:
  #   linux:
  #     operatingSystem: 'ubuntu-latest'
    # mac:
    #   operatingSystem: 'macos-latest'

pool:
  vmImage: 'ubuntu-latest'
  # vmImage: $(operatingSystem)

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the build"
- stage: DeployJob
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy: 
      runOnce:
        deploy:
          steps:
            - script: echo deploy to Dev
- stage: QAJob
  jobs:
  - deployment: QAJob
    environment: QA
    strategy: 
      runOnce:
        deploy:
          steps:
            - script: echo deploy to QA

