trigger:
- main

resources:
- repo: self

variables:
  # tag: '$(Build.BuildId)'
  tag: 13

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:


#stage 1
# build docker image
    # - task: Docker@2
      # displayName: Build an image
      # inputs:
      #   containerRegistry: 'mosabami-docker-hub'
      #   repository: 'mosabami/currency-exchange-devops'
      #   command: 'buildAndPush'
      #   Dockerfile: '**/Dockerfile'
      #   tags: '$(tag)'
# publish kubernetes config file
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'
#stage 2
# download the k8s files
- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
# deploy to cluster
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'azure-kubernetes-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'mosabami/currency-exchange-devops:$(tag)'


